// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.vic.poker.pokerclient;

public final class PokerClient_Stub
    extends java.rmi.server.RemoteStub
    implements com.vic.poker.client.Client, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_endGame_0;
    private static java.lang.reflect.Method $method_getName_1;
    private static java.lang.reflect.Method $method_getResultCard_2;
    private static java.lang.reflect.Method $method_printCard_3;
    private static java.lang.reflect.Method $method_startGame_4;
    
    static {
	try {
	    $method_endGame_0 = com.vic.poker.client.Client.class.getMethod("endGame", new java.lang.Class[] {});
	    $method_getName_1 = com.vic.poker.client.Client.class.getMethod("getName", new java.lang.Class[] {});
	    $method_getResultCard_2 = com.vic.poker.client.Client.class.getMethod("getResultCard", new java.lang.Class[] {});
	    $method_printCard_3 = com.vic.poker.client.Client.class.getMethod("printCard", new java.lang.Class[] {});
	    $method_startGame_4 = com.vic.poker.client.Client.class.getMethod("startGame", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PokerClient_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of endGame()
    public void endGame()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_endGame_0, null, 258781963203249526L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getName()
    public void getName()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_getName_1, null, -2704301216624735055L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getResultCard()
    public void getResultCard()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_getResultCard_2, null, -3249845929072415502L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of printCard()
    public void printCard()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_printCard_3, null, 1377309457055294723L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of startGame()
    public void startGame()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_startGame_4, null, 7826272692900709118L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
